"""Módulo de utilitários do HealthPlan.AI.Assistant."""

from .api_client import HealthPlanAPIClient
from .formatters import (
    format_company,
    format_companies,
    format_healthplan,
    format_healthplans,
    format_beneficiary,
    format_beneficiaries,
    format_quote,
    format_quotes,
    format_coverage,
    format_coverages,
    format_agerange,
    format_ageranges,
    format_accommodation,
    format_accommodations,
    format_error,
    format_success,
)
from .validators import (
    validate_company_data,
    validate_healthplan_data,
    validate_beneficiary_data,
    validate_quote_data,
    validate_coverage_data,
    validate_agerange_data,
    validate_accommodation_data,
    validate_id,
)

__all__ = [
    "HealthPlanAPIClient",
    "format_company",
    "format_companies",
    "format_healthplan",
    "format_healthplans",
    "format_beneficiary",
    "format_beneficiaries",
    "format_quote",
    "format_quotes",
    "format_coverage",
    "format_coverages",
    "format_agerange",
    "format_ageranges",
    "format_accommodation",
    "format_accommodations",
    "format_error",
    "format_success",
    "validate_company_data",
    "validate_healthplan_data",
    "validate_beneficiary_data",
    "validate_quote_data",
    "validate_coverage_data",
    "validate_agerange_data",
    "validate_accommodation_data",
    "validate_id",
]
