//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanTemplate.API.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceStartup {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceStartup() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CleanTemplate.API.Resource.ResourceStartup", typeof(ResourceStartup).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string AccountController {
            get {
                return ResourceManager.GetString("AccountController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccountClaimAction.
        /// </summary>
        public static string AccountClaimActionController {
            get {
                return ResourceManager.GetString("AccountClaimActionController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Control API.
        /// </summary>
        public static string AccessControlApiDisplayName {
            get {
                return ResourceManager.GetString("AccessControlApiDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string ActionController {
            get {
                return ResourceManager.GetString("ActionController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication API.
        /// </summary>
        public static string AuthenticationApiDisplayName {
            get {
                return ResourceManager.GetString("AuthenticationApiDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        public static string AuthenticationController {
            get {
                return ResourceManager.GetString("AuthenticationController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim.
        /// </summary>
        public static string ClaimController {
            get {
                return ResourceManager.GetString("ClaimController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClaimAction.
        /// </summary>
        public static string ClaimActionController {
            get {
                return ResourceManager.GetString("ClaimActionController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API endpoints for managing access control including accounts, claims, and actions.
        /// </summary>
        public static string SwaggerAccessControlDescription {
            get {
                return ResourceManager.GetString("SwaggerAccessControlDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API endpoints for user authentication and token management.
        /// </summary>
        public static string SwaggerAuthenticationDescription {
            get {
                return ResourceManager.GetString("SwaggerAuthenticationDescription", resourceCulture);
            }
        }
    }
}