//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanTemplate.API.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceAPI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceAPI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CleanTemplate.API.Resource.ResourceAPI", typeof(ResourceAPI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account claim action created successfully..
        /// </summary>
        public static string AccountClaimActionCreatedSuccessfully {
            get {
                return ResourceManager.GetString("AccountClaimActionCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account claim action deleted successfully..
        /// </summary>
        public static string AccountClaimActionDeletedSuccessfully {
            get {
                return ResourceManager.GetString("AccountClaimActionDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account claim action not found..
        /// </summary>
        public static string AccountClaimActionNotFound {
            get {
                return ResourceManager.GetString("AccountClaimActionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account claim action retrieved successfully..
        /// </summary>
        public static string AccountClaimActionRetrievedSuccessfully {
            get {
                return ResourceManager.GetString("AccountClaimActionRetrievedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account claim actions retrieved successfully..
        /// </summary>
        public static string AccountClaimActionsRetrievedSuccessfully {
            get {
                return ResourceManager.GetString("AccountClaimActionsRetrievedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account claim action updated successfully..
        /// </summary>
        public static string AccountClaimActionUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("AccountClaimActionUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account created successfully..
        /// </summary>
        public static string AccountCreatedSuccessfully {
            get {
                return ResourceManager.GetString("AccountCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action created successfully..
        /// </summary>
        public static string ActionCreatedSuccessfully {
            get {
                return ResourceManager.GetString("ActionCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action deleted successfully..
        /// </summary>
        public static string ActionDeletedSuccessfully {
            get {
                return ResourceManager.GetString("ActionDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action not found..
        /// </summary>
        public static string ActionNotFound {
            get {
                return ResourceManager.GetString("ActionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action retrieved successfully..
        /// </summary>
        public static string ActionRetrievedSuccessfully {
            get {
                return ResourceManager.GetString("ActionRetrievedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions retrieved successfully..
        /// </summary>
        public static string ActionsRetrievedSuccessfully {
            get {
                return ResourceManager.GetString("ActionsRetrievedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action updated successfully..
        /// </summary>
        public static string ActionUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("ActionUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new account..
        /// </summary>
        public static string AddAccount {
            get {
                return ResourceManager.GetString("AddAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete account.
        /// </summary>
        public static string DeleteAccount {
            get {
                return ResourceManager.GetString("DeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get account by ID.
        /// </summary>
        public static string GetAccountById {
            get {
                return ResourceManager.GetString("GetAccountById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get all accounts.
        /// </summary>
        public static string GetAccounts {
            get {
                return ResourceManager.GetString("GetAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update account.
        /// </summary>
        public static string UpdateAccount {
            get {
                return ResourceManager.GetString("UpdateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new account claim action.
        /// </summary>
        public static string AddAccountClaimAction {
            get {
                return ResourceManager.GetString("AddAccountClaimAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new action.
        /// </summary>
        public static string AddAction {
            get {
                return ResourceManager.GetString("AddAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new claim.
        /// </summary>
        public static string AddClaim {
            get {
                return ResourceManager.GetString("AddClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new claim action.
        /// </summary>
        public static string AddClaimAction {
            get {
                return ResourceManager.GetString("AddClaimAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred..
        /// </summary>
        public static string AnUnexpectedErrorOccurred {
            get {
                return ResourceManager.GetString("AnUnexpectedErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred and the account claim action could not be deleted..
        /// </summary>
        public static string AnUnexpectedErrorOccurredAccountClaimActionCouldNotBeDeleted {
            get {
                return ResourceManager.GetString("AnUnexpectedErrorOccurredAccountClaimActionCouldNotBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred and the account claim action could not be inserted..
        /// </summary>
        public static string AnUnexpectedErrorOccurredAccountClaimActionCouldNotBeInserted {
            get {
                return ResourceManager.GetString("AnUnexpectedErrorOccurredAccountClaimActionCouldNotBeInserted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred and the account claim action could not be retrieved..
        /// </summary>
        public static string AnUnexpectedErrorOccurredAccountClaimActionCouldNotBeRetrieved {
            get {
                return ResourceManager.GetString("AnUnexpectedErrorOccurredAccountClaimActionCouldNotBeRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred and the account claim action could not be updated..
        /// </summary>
        public static string AnUnexpectedErrorOccurredAccountClaimActionCouldNotBeUpdated {
            get {
                return ResourceManager.GetString("AnUnexpectedErrorOccurredAccountClaimActionCouldNotBeUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred and the account claim actions could not be retrieved..
        /// </summary>
        public static string AnUnexpectedErrorOccurredAccountClaimActionsCouldNotBeRetrieved {
            get {
                return ResourceManager.GetString("AnUnexpectedErrorOccurredAccountClaimActionsCouldNotBeRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred and the account could not be inserted..
        /// </summary>
        public static string AnUnexpectedErrorOccurredAccountCouldInserted {
            get {
                return ResourceManager.GetString("AnUnexpectedErrorOccurredAccountCouldInserted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account not found..
        /// </summary>
        public static string AccountNotFound {
            get {
                return ResourceManager.GetString("AccountNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account retrieved successfully..
        /// </summary>
        public static string AccountRetrievedSuccessfully {
            get {
                return ResourceManager.GetString("AccountRetrievedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts retrieved successfully..
        /// </summary>
        public static string AccountsRetrievedSuccessfully {
            get {
                return ResourceManager.GetString("AccountsRetrievedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account updated successfully..
        /// </summary>
        public static string AccountUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("AccountUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account deleted successfully..
        /// </summary>
        public static string AccountDeletedSuccessfully {
            get {
                return ResourceManager.GetString("AccountDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred and the account could not be retrieved..
        /// </summary>
        public static string AnUnexpectedErrorOccurredAccountCouldNotBeRetrieved {
            get {
                return ResourceManager.GetString("AnUnexpectedErrorOccurredAccountCouldNotBeRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred and the accounts could not be retrieved..
        /// </summary>
        public static string AnUnexpectedErrorOccurredAccountsCouldNotBeRetrieved {
            get {
                return ResourceManager.GetString("AnUnexpectedErrorOccurredAccountsCouldNotBeRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred and the account could not be updated..
        /// </summary>
        public static string AnUnexpectedErrorOccurredAccountCouldNotBeUpdated {
            get {
                return ResourceManager.GetString("AnUnexpectedErrorOccurredAccountCouldNotBeUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred and the account could not be deleted..
        /// </summary>
        public static string AnUnexpectedErrorOccurredAccountCouldNotBeDeleted {
            get {
                return ResourceManager.GetString("AnUnexpectedErrorOccurredAccountCouldNotBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred and the action could not be deleted..
        /// </summary>
        public static string AnUnexpectedErrorOccurredActionCouldNotBeDeleted {
            get {
                return ResourceManager.GetString("AnUnexpectedErrorOccurredActionCouldNotBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred and the action could not be inserted..
        /// </summary>
        public static string AnUnexpectedErrorOccurredActionCouldNotBeInserted {
            get {
                return ResourceManager.GetString("AnUnexpectedErrorOccurredActionCouldNotBeInserted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred and the action could not be retrieved..
        /// </summary>
        public static string AnUnexpectedErrorOccurredActionCouldNotBeRetrieved {
            get {
                return ResourceManager.GetString("AnUnexpectedErrorOccurredActionCouldNotBeRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred and the action could not be updated..
        /// </summary>
        public static string AnUnexpectedErrorOccurredActionCouldNotBeUpdated {
            get {
                return ResourceManager.GetString("AnUnexpectedErrorOccurredActionCouldNotBeUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred and the actions could not be retrieved..
        /// </summary>
        public static string AnUnexpectedErrorOccurredActionsCouldNotBeRetrieved {
            get {
                return ResourceManager.GetString("AnUnexpectedErrorOccurredActionsCouldNotBeRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred and the claim action could not be deleted..
        /// </summary>
        public static string AnUnexpectedErrorOccurredClaimActionCouldNotBeDeleted {
            get {
                return ResourceManager.GetString("AnUnexpectedErrorOccurredClaimActionCouldNotBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred and the claim action could not be inserted..
        /// </summary>
        public static string AnUnexpectedErrorOccurredClaimActionCouldNotBeInserted {
            get {
                return ResourceManager.GetString("AnUnexpectedErrorOccurredClaimActionCouldNotBeInserted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred and the claim action could not be retrieved..
        /// </summary>
        public static string AnUnexpectedErrorOccurredClaimActionCouldNotBeRetrieved {
            get {
                return ResourceManager.GetString("AnUnexpectedErrorOccurredClaimActionCouldNotBeRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred and the claim action could not be updated..
        /// </summary>
        public static string AnUnexpectedErrorOccurredClaimActionCouldNotBeUpdated {
            get {
                return ResourceManager.GetString("AnUnexpectedErrorOccurredClaimActionCouldNotBeUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred and the claim actions could not be retrieved..
        /// </summary>
        public static string AnUnexpectedErrorOccurredClaimActionsCouldNotBeRetrieved {
            get {
                return ResourceManager.GetString("AnUnexpectedErrorOccurredClaimActionsCouldNotBeRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred and the claim could not be deleted..
        /// </summary>
        public static string AnUnexpectedErrorOccurredClaimCouldNotBeDeleted {
            get {
                return ResourceManager.GetString("AnUnexpectedErrorOccurredClaimCouldNotBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred and the claim could not be inserted..
        /// </summary>
        public static string AnUnexpectedErrorOccurredClaimCouldNotBeInserted {
            get {
                return ResourceManager.GetString("AnUnexpectedErrorOccurredClaimCouldNotBeInserted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred and the claim could not be retrieved..
        /// </summary>
        public static string AnUnexpectedErrorOccurredClaimCouldNotBeRetrieved {
            get {
                return ResourceManager.GetString("AnUnexpectedErrorOccurredClaimCouldNotBeRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred and the claim could not be updated..
        /// </summary>
        public static string AnUnexpectedErrorOccurredClaimCouldNotBeUpdated {
            get {
                return ResourceManager.GetString("AnUnexpectedErrorOccurredClaimCouldNotBeUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred and the claims could not be retrieved..
        /// </summary>
        public static string AnUnexpectedErrorOccurredClaimsCouldNotBeRetrieved {
            get {
                return ResourceManager.GetString("AnUnexpectedErrorOccurredClaimsCouldNotBeRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred and the token could not be generated..
        /// </summary>
        public static string AnUnexpectedErrorOccurredTokenCouldGenerated {
            get {
                return ResourceManager.GetString("AnUnexpectedErrorOccurredTokenCouldGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled exception occurred..
        /// </summary>
        public static string AnUnhandledExceptionOccurred {
            get {
                return ResourceManager.GetString("AnUnhandledExceptionOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API for user authentication and account management..
        /// </summary>
        public static string APIManagement {
            get {
                return ResourceManager.GetString("APIManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication failed - Invalid credentials..
        /// </summary>
        public static string AuthenticationFailedInvalidCredentials {
            get {
                return ResourceManager.GetString("AuthenticationFailedInvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim action created successfully..
        /// </summary>
        public static string ClaimActionCreatedSuccessfully {
            get {
                return ResourceManager.GetString("ClaimActionCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim action deleted successfully..
        /// </summary>
        public static string ClaimActionDeletedSuccessfully {
            get {
                return ResourceManager.GetString("ClaimActionDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim action not found..
        /// </summary>
        public static string ClaimActionNotFound {
            get {
                return ResourceManager.GetString("ClaimActionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim action retrieved successfully..
        /// </summary>
        public static string ClaimActionRetrievedSuccessfully {
            get {
                return ResourceManager.GetString("ClaimActionRetrievedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim actions retrieved successfully..
        /// </summary>
        public static string ClaimActionsRetrievedSuccessfully {
            get {
                return ResourceManager.GetString("ClaimActionsRetrievedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim action updated successfully..
        /// </summary>
        public static string ClaimActionUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("ClaimActionUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim created successfully..
        /// </summary>
        public static string ClaimCreatedSuccessfully {
            get {
                return ResourceManager.GetString("ClaimCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim deleted successfully..
        /// </summary>
        public static string ClaimDeletedSuccessfully {
            get {
                return ResourceManager.GetString("ClaimDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim not found..
        /// </summary>
        public static string ClaimNotFound {
            get {
                return ResourceManager.GetString("ClaimNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim retrieved successfully..
        /// </summary>
        public static string ClaimRetrievedSuccessfully {
            get {
                return ResourceManager.GetString("ClaimRetrievedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claims retrieved successfully..
        /// </summary>
        public static string ClaimsRetrievedSuccessfully {
            get {
                return ResourceManager.GetString("ClaimsRetrievedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim updated successfully..
        /// </summary>
        public static string ClaimUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("ClaimUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete account claim action.
        /// </summary>
        public static string DeleteAccountClaimAction {
            get {
                return ResourceManager.GetString("DeleteAccountClaimAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete action.
        /// </summary>
        public static string DeleteAction {
            get {
                return ResourceManager.GetString("DeleteAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete claim.
        /// </summary>
        public static string DeleteClaim {
            get {
                return ResourceManager.GetString("DeleteClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete claim action.
        /// </summary>
        public static string DeleteClaimAction {
            get {
                return ResourceManager.GetString("DeleteClaimAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performs the account creation process using the provided user information..
        /// </summary>
        public static string DocumentationAddAccount {
            get {
                return ResourceManager.GetString("DocumentationAddAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes a user account from the system by its unique identifier..
        /// </summary>
        public static string DocumentationDeleteAccount {
            get {
                return ResourceManager.GetString("DocumentationDeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieves a specific user account by its unique identifier..
        /// </summary>
        public static string DocumentationGetAccountById {
            get {
                return ResourceManager.GetString("DocumentationGetAccountById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieves all user accounts in the system..
        /// </summary>
        public static string DocumentationGetAccounts {
            get {
                return ResourceManager.GetString("DocumentationGetAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates an existing user account with the provided information..
        /// </summary>
        public static string DocumentationUpdateAccount {
            get {
                return ResourceManager.GetString("DocumentationUpdateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a new account claim action association with the provided information..
        /// </summary>
        public static string DocumentationAddAccountClaimAction {
            get {
                return ResourceManager.GetString("DocumentationAddAccountClaimAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a new action with the provided information..
        /// </summary>
        public static string DocumentationAddAction {
            get {
                return ResourceManager.GetString("DocumentationAddAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a new claim with the provided information..
        /// </summary>
        public static string DocumentationAddClaim {
            get {
                return ResourceManager.GetString("DocumentationAddClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a new claim action with the provided information..
        /// </summary>
        public static string DocumentationAddClaimAction {
            get {
                return ResourceManager.GetString("DocumentationAddClaimAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes an account claim action association from the system..
        /// </summary>
        public static string DocumentationDeleteAccountClaimAction {
            get {
                return ResourceManager.GetString("DocumentationDeleteAccountClaimAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes an action from the system by its unique identifier..
        /// </summary>
        public static string DocumentationDeleteAction {
            get {
                return ResourceManager.GetString("DocumentationDeleteAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes a claim from the system by its unique identifier..
        /// </summary>
        public static string DocumentationDeleteClaim {
            get {
                return ResourceManager.GetString("DocumentationDeleteClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes a claim action from the system by its unique identifier..
        /// </summary>
        public static string DocumentationDeleteClaimAction {
            get {
                return ResourceManager.GetString("DocumentationDeleteClaimAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performs the user authentication process using the provided credentials. .
        /// </summary>
        public static string DocumentationGenerateToken {
            get {
                return ResourceManager.GetString("DocumentationGenerateToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieves a specific account claim action by account ID and claim action ID..
        /// </summary>
        public static string DocumentationGetAccountClaimActionById {
            get {
                return ResourceManager.GetString("DocumentationGetAccountClaimActionById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieves account claim actions, optionally filtered by account ID or claim action ID..
        /// </summary>
        public static string DocumentationGetAccountClaimActions {
            get {
                return ResourceManager.GetString("DocumentationGetAccountClaimActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieves a specific action by its unique identifier..
        /// </summary>
        public static string DocumentationGetActionById {
            get {
                return ResourceManager.GetString("DocumentationGetActionById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieves all available actions in the system..
        /// </summary>
        public static string DocumentationGetActions {
            get {
                return ResourceManager.GetString("DocumentationGetActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieves a specific claim action by its unique identifier..
        /// </summary>
        public static string DocumentationGetClaimActionById {
            get {
                return ResourceManager.GetString("DocumentationGetClaimActionById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieves all available claim actions in the system..
        /// </summary>
        public static string DocumentationGetClaimActions {
            get {
                return ResourceManager.GetString("DocumentationGetClaimActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieves a specific claim by its unique identifier..
        /// </summary>
        public static string DocumentationGetClaimById {
            get {
                return ResourceManager.GetString("DocumentationGetClaimById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieves all available claims in the system..
        /// </summary>
        public static string DocumentationGetClaims {
            get {
                return ResourceManager.GetString("DocumentationGetClaims", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates an existing account claim action association with the provided information..
        /// </summary>
        public static string DocumentationUpdateAccountClaimAction {
            get {
                return ResourceManager.GetString("DocumentationUpdateAccountClaimAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates an existing action with the provided information..
        /// </summary>
        public static string DocumentationUpdateAction {
            get {
                return ResourceManager.GetString("DocumentationUpdateAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates an existing claim with the provided information..
        /// </summary>
        public static string DocumentationUpdateClaim {
            get {
                return ResourceManager.GetString("DocumentationUpdateClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates an existing claim action with the provided information..
        /// </summary>
        public static string DocumentationUpdateClaimAction {
            get {
                return ResourceManager.GetString("DocumentationUpdateClaimAction", resourceCulture);
            }
        }
        

        /// <summary>
        ///   Looks up a localized string similar to Get account claim action by IDs.
        /// </summary>
        public static string GetAccountClaimActionById {
            get {
                return ResourceManager.GetString("GetAccountClaimActionById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get account claim actions.
        /// </summary>
        public static string GetAccountClaimActions {
            get {
                return ResourceManager.GetString("GetAccountClaimActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get action by ID.
        /// </summary>
        public static string GetActionById {
            get {
                return ResourceManager.GetString("GetActionById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get all actions.
        /// </summary>
        public static string GetActions {
            get {
                return ResourceManager.GetString("GetActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get claim action by ID.
        /// </summary>
        public static string GetClaimActionById {
            get {
                return ResourceManager.GetString("GetClaimActionById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get all claim actions.
        /// </summary>
        public static string GetClaimActions {
            get {
                return ResourceManager.GetString("GetClaimActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get claim by ID.
        /// </summary>
        public static string GetClaimById {
            get {
                return ResourceManager.GetString("GetClaimById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get all claims.
        /// </summary>
        public static string GetClaims {
            get {
                return ResourceManager.GetString("GetClaims", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal server error..
        /// </summary>
        public static string InternalServerError {
            get {
                return ResourceManager.GetString("InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data or validation error..
        /// </summary>
        public static string InvalidDataValidationError {
            get {
                return ResourceManager.GetString("InvalidDataValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid request..
        /// </summary>
        public static string InvalidRequest {
            get {
                return ResourceManager.GetString("InvalidRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found..
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK..
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more validation errors occurred..
        /// </summary>
        public static string OneOrMoreValidationErrorsOccurred {
            get {
                return ResourceManager.GetString("OneOrMoreValidationErrorsOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request was successful..
        /// </summary>
        public static string RequestWasSuccessful {
            get {
                return ResourceManager.GetString("RequestWasSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested resource was not found..
        /// </summary>
        public static string TheRequestedResourceWasNotFound {
            get {
                return ResourceManager.GetString("TheRequestedResourceWasNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token generated successfully..
        /// </summary>
        public static string TokenGeneratedSuccessfully {
            get {
                return ResourceManager.GetString("TokenGeneratedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized..
        /// </summary>
        public static string Unauthorized {
            get {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update account claim action.
        /// </summary>
        public static string UpdateAccountClaimAction {
            get {
                return ResourceManager.GetString("UpdateAccountClaimAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update action.
        /// </summary>
        public static string UpdateAction {
            get {
                return ResourceManager.GetString("UpdateAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update claim.
        /// </summary>
        public static string UpdateClaim {
            get {
                return ResourceManager.GetString("UpdateClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update claim action.
        /// </summary>
        public static string UpdateClaimAction {
            get {
                return ResourceManager.GetString("UpdateClaimAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not authorized..
        /// </summary>
        public static string UserNotAuthorized {
            get {
                return ResourceManager.GetString("UserNotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflict..
        /// </summary>
        public static string Conflict {
            get {
                return ResourceManager.GetString("Conflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request conflicts with the current state of the resource..
        /// </summary>
        public static string RequestConflictsWithCurrentState {
            get {
                return ResourceManager.GetString("RequestConflictsWithCurrentState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller responsible for managing actions in the system. Provides CRUD operations for actions that can be combined with claims to form permissions. Actions define what operations can be performed on resources in the RBAC system..
        /// </summary>
        public static string ActionControllerDescription {
            get {
                return ResourceManager.GetString("ActionControllerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller responsible for managing user accounts in the system. Provides CRUD operations for user accounts, including account creation, retrieval, updates, and deletion. Handles account management operations with proper authentication and authorization controls..
        /// </summary>
        public static string AccountControllerDescription {
            get {
                return ResourceManager.GetString("AccountControllerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller responsible for managing account-claim-action associations in the RBAC system. Provides CRUD operations for linking user accounts with specific claim-action permissions. Enables fine-grained access control by assigning specific permissions to individual accounts..
        /// </summary>
        public static string AccountClaimActionControllerDescription {
            get {
                return ResourceManager.GetString("AccountClaimActionControllerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller responsible for managing claim-action associations in the RBAC system. Provides CRUD operations for linking claims with actions to create specific permissions. Claim-actions define what operations (actions) can be performed on specific resources (claims)..
        /// </summary>
        public static string ClaimActionControllerDescription {
            get {
                return ResourceManager.GetString("ClaimActionControllerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller for managing claims in the Role-Based Access Control (RBAC) system. Provides CRUD operations for claims (permissions/roles) that can be assigned to users. Claims are fundamental building blocks for the authorization system..
        /// </summary>
        public static string ClaimControllerDescription {
            get {
                return ResourceManager.GetString("ClaimControllerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller responsible for handling authentication operations. Provides endpoints for user authentication..
        /// </summary>
        public static string AuthenticationControllerDescription {
            get {
                return ResourceManager.GetString("AuthenticationControllerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication API.
        /// </summary>
        public static string AuthenticationApiTitle {
            get {
                return ResourceManager.GetString("AuthenticationApiTitle", resourceCulture);
            }
        }
    }
}
