//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanTemplate.Application.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceLogin {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceLogin() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CleanTemplate.Application.Resource.ResourceLogin", typeof(ResourceLogin).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account not found..
        /// </summary>
        public static string AccountNotFound {
            get {
                return ResourceManager.GetString("AccountNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password..
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot contain spaces or be null/empty..
        /// </summary>
        public static string PasswordCannotContainSpacesNullEmpty {
            get {
                return ResourceManager.GetString("PasswordCannotContainSpacesNullEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 6 characters..
        /// </summary>
        public static string PasswordMustLeast6Characters {
            get {
                return ResourceManager.GetString("PasswordMustLeast6Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passsword must be at most 50 characters..
        /// </summary>
        public static string PasswordMustMost50Characters {
            get {
                return ResourceManager.GetString("PasswordMustMost50Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required..
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName cannot contain spaces or be null/empty..
        /// </summary>
        public static string UserNameCannotContainSpacesNullEmpty {
            get {
                return ResourceManager.GetString("UserNameCannotContainSpacesNullEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName must be at least 6 characters..
        /// </summary>
        public static string UserNameMustLeast6Characters {
            get {
                return ResourceManager.GetString("UserNameMustLeast6Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName must be at most 50 characters..
        /// </summary>
        public static string UserNameMustMost50Characters {
            get {
                return ResourceManager.GetString("UserNameMustMost50Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName is required.
        /// </summary>
        public static string UserNameRequired {
            get {
                return ResourceManager.GetString("UserNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An account with this username already exists..
        /// </summary>
        public static string DuplicateUserName {
            get {
                return ResourceManager.GetString("DuplicateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account ID is required..
        /// </summary>
        public static string IdAccountRequired {
            get {
                return ResourceManager.GetString("IdAccountRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account ID must be a positive number..
        /// </summary>
        public static string IdAccountMustBePositive {
            get {
                return ResourceManager.GetString("IdAccountMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim Action ID is required..
        /// </summary>
        public static string IdClaimActionRequired {
            get {
                return ResourceManager.GetString("IdClaimActionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim Action ID must be a positive number..
        /// </summary>
        public static string IdClaimActionMustBePositive {
            get {
                return ResourceManager.GetString("IdClaimActionMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim ID is required..
        /// </summary>
        public static string IdClaimRequired {
            get {
                return ResourceManager.GetString("IdClaimRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim ID must be a positive number..
        /// </summary>
        public static string IdClaimMustBePositive {
            get {
                return ResourceManager.GetString("IdClaimMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action ID is required..
        /// </summary>
        public static string IdActionRequired {
            get {
                return ResourceManager.GetString("IdActionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action ID must be a positive number..
        /// </summary>
        public static string IdActionMustBePositive {
            get {
                return ResourceManager.GetString("IdActionMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action name is required..
        /// </summary>
        public static string ActionNameRequired {
            get {
                return ResourceManager.GetString("ActionNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action name cannot contain spaces or be null/empty..
        /// </summary>
        public static string ActionNameCannotContainSpaces {
            get {
                return ResourceManager.GetString("ActionNameCannotContainSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action name must be at least 1 character..
        /// </summary>
        public static string ActionNameMustLeast1Character {
            get {
                return ResourceManager.GetString("ActionNameMustLeast1Character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action name must be at most 100 characters..
        /// </summary>
        public static string ActionNameMustMost100Characters {
            get {
                return ResourceManager.GetString("ActionNameMustMost100Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim type is required..
        /// </summary>
        public static string ClaimTypeRequired {
            get {
                return ResourceManager.GetString("ClaimTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim value is required..
        /// </summary>
        public static string ClaimValueRequired {
            get {
                return ResourceManager.GetString("ClaimValueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim value must be at least 1 character..
        /// </summary>
        public static string ClaimValueMustLeast1Character {
            get {
                return ResourceManager.GetString("ClaimValueMustLeast1Character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim value must be at most 200 characters..
        /// </summary>
        public static string ClaimValueMustMost200Characters {
            get {
                return ResourceManager.GetString("ClaimValueMustMost200Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim description must be at most 500 characters..
        /// </summary>
        public static string ClaimDescriptionMustMost500Characters {
            get {
                return ResourceManager.GetString("ClaimDescriptionMustMost500Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreatedBy is required for audit tracking..
        /// </summary>
        public static string CreatedByRequired {
            get {
                return ResourceManager.GetString("CreatedByRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreatedBy must be at most 100 characters..
        /// </summary>
        public static string CreatedByMustMost100Characters {
            get {
                return ResourceManager.GetString("CreatedByMustMost100Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdatedBy must be at most 100 characters..
        /// </summary>
        public static string UpdatedByMustMost100Characters {
            get {
                return ResourceManager.GetString("UpdatedByMustMost100Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeletedBy must be at most 100 characters..
        /// </summary>
        public static string DeletedByMustMost100Characters {
            get {
                return ResourceManager.GetString("DeletedByMustMost100Characters", resourceCulture);
            }
        }
    }
}
